// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source=deps.go -destination=./mocks/mock.go
//

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	context "context"
	reflect "reflect"

	log "github.com/AndyS1mpson/key-value-database/internal/database/storage/wal/log"
	concurrency "github.com/AndyS1mpson/key-value-database/internal/utils/concurrency"
	gomock "go.uber.org/mock/gomock"
)

// Mockengine is a mock of engine interface.
type Mockengine struct {
	ctrl     *gomock.Controller
	recorder *MockengineMockRecorder
	isgomock struct{}
}

// MockengineMockRecorder is the mock recorder for Mockengine.
type MockengineMockRecorder struct {
	mock *Mockengine
}

// NewMockengine creates a new mock instance.
func NewMockengine(ctrl *gomock.Controller) *Mockengine {
	mock := &Mockengine{ctrl: ctrl}
	mock.recorder = &MockengineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockengine) EXPECT() *MockengineMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *Mockengine) Del(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Del", arg0, arg1)
}

// Del indicates an expected call of Del.
func (mr *MockengineMockRecorder) Del(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*Mockengine)(nil).Del), arg0, arg1)
}

// Get mocks base method.
func (m *Mockengine) Get(arg0 context.Context, arg1 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockengineMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockengine)(nil).Get), arg0, arg1)
}

// Set mocks base method.
func (m *Mockengine) Set(arg0 context.Context, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0, arg1, arg2)
}

// Set indicates an expected call of Set.
func (mr *MockengineMockRecorder) Set(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*Mockengine)(nil).Set), arg0, arg1, arg2)
}

// Mockwal is a mock of wal interface.
type Mockwal struct {
	ctrl     *gomock.Controller
	recorder *MockwalMockRecorder
	isgomock struct{}
}

// MockwalMockRecorder is the mock recorder for Mockwal.
type MockwalMockRecorder struct {
	mock *Mockwal
}

// NewMockwal creates a new mock instance.
func NewMockwal(ctrl *gomock.Controller) *Mockwal {
	mock := &Mockwal{ctrl: ctrl}
	mock.recorder = &MockwalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockwal) EXPECT() *MockwalMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *Mockwal) Del(ctx context.Context, key string) concurrency.FutureError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(concurrency.FutureError)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockwalMockRecorder) Del(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*Mockwal)(nil).Del), ctx, key)
}

// Recover mocks base method.
func (m *Mockwal) Recover() ([]log.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recover")
	ret0, _ := ret[0].([]log.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recover indicates an expected call of Recover.
func (mr *MockwalMockRecorder) Recover() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recover", reflect.TypeOf((*Mockwal)(nil).Recover))
}

// Set mocks base method.
func (m *Mockwal) Set(ctx context.Context, key, value string) concurrency.FutureError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(concurrency.FutureError)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockwalMockRecorder) Set(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*Mockwal)(nil).Set), ctx, key, value)
}

// MockReplica is a mock of Replica interface.
type MockReplica struct {
	ctrl     *gomock.Controller
	recorder *MockReplicaMockRecorder
	isgomock struct{}
}

// MockReplicaMockRecorder is the mock recorder for MockReplica.
type MockReplicaMockRecorder struct {
	mock *MockReplica
}

// NewMockReplica creates a new mock instance.
func NewMockReplica(ctrl *gomock.Controller) *MockReplica {
	mock := &MockReplica{ctrl: ctrl}
	mock.recorder = &MockReplicaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplica) EXPECT() *MockReplicaMockRecorder {
	return m.recorder
}

// IsMaster mocks base method.
func (m *MockReplica) IsMaster() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMaster")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsMaster indicates an expected call of IsMaster.
func (mr *MockReplicaMockRecorder) IsMaster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMaster", reflect.TypeOf((*MockReplica)(nil).IsMaster))
}
